version: "3"

services:
  app-demo-1:
    build:
      context: app-demo-1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  app-demo-2:
    build:
      context: app-demo-2
      dockerfile: Dockerfile
    ports:
      - "80:80"
