version: "3"

services:
  app-demo-1:
    build:
      context: app-demo-1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: 845563949565.dkr.ecr.ap-southeast-1.amazonaws.com/aws-ecr-kubenginx:app-demo-1-${BUILD_VERSION}

  app-demo-2:
    build:
      context: app-demo-2
      dockerfile: Dockerfile
    ports:
      - "80:80"
    image: 845563949565.dkr.ecr.ap-southeast-1.amazonaws.com/aws-ecr-kubenginx:app-demo-2-${BUILD_VERSION}
